projectName: primary-appset-4

services:
  list-app-4-1:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-1
  list-app-4-2:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-2
  list-app-4-3:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-3
  list-app-4-4:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-4
  list-app-4-5:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-5
  list-app-4-6:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-6
  list-app-4-7:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-7
  list-app-4-8:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-8
  list-app-4-9:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-9
  list-app-4-10:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-10
  list-app-4-11:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-11
  list-app-4-12:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-12
  list-app-4-13:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-13
  list-app-4-14:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-14
  list-app-4-15:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-15
  list-app-4-16:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-16
  list-app-4-17:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-17
  list-app-4-18:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-18
  list-app-4-19:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-19
  list-app-4-20:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-20
  list-app-4-21:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-21
  list-app-4-22:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-22
  list-app-4-23:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-23
  list-app-4-24:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-24
  list-app-4-25:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-25
  list-app-4-26:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-26
  list-app-4-27:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-27
  list-app-4-28:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-28
  list-app-4-29:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-29
  list-app-4-30:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-30
  list-app-4-31:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-31
  list-app-4-32:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-32
  list-app-4-33:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-33
  list-app-4-34:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-34
  list-app-4-35:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-35
  list-app-4-36:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-36
  list-app-4-37:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-37
  list-app-4-38:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-38
  list-app-4-39:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-39
  list-app-4-40:
    repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
    targetRevision: master
    path: list-app-4-40
