kindSetName: "multinode-kindset"
projectName: "list-appset"
chartRepo:
  path: "appset"
  revision: "master"
kinds:
  - kind-cluster-01
  - kind-cluster-02
  - kind-cluster-03
  - kind-cluster-04
  - kind-cluster-05
  - kind-cluster-06
  - kind-cluster-07
  - kind-cluster-08
  - kind-cluster-09
  - kind-cluster-10
  - kind-cluster-11
  - kind-cluster-12
  - kind-cluster-13
  - kind-cluster-14
  - kind-cluster-15
  - kind-cluster-16
  - kind-cluster-17
  - kind-cluster-18
  - kind-cluster-19
  - kind-cluster-20
  - kind-cluster-21
  - kind-cluster-22
  - kind-cluster-23
  - kind-cluster-24
  - kind-cluster-25
  - kind-cluster-26
  - kind-cluster-27
  - kind-cluster-28
  - kind-cluster-29
  - kind-cluster-30
  - kind-cluster-31
  - kind-cluster-32
  - kind-cluster-33
  - kind-cluster-34
  - kind-cluster-35
  - kind-cluster-36
  - kind-cluster-37
  - kind-cluster-38
  - kind-cluster-39
  - kind-cluster-40
  - kind-cluster-41
  - kind-cluster-42
  - kind-cluster-43
  - kind-cluster-44
  - kind-cluster-45
  - kind-cluster-46
  - kind-cluster-47
  - kind-cluster-48
  - kind-cluster-49
  - kind-cluster-50
  - kind-cluster-51
  - kind-cluster-52
  - kind-cluster-53
  - kind-cluster-54
  - kind-cluster-55
  - kind-cluster-56
  - kind-cluster-57
  - kind-cluster-58
  - kind-cluster-59
  - kind-cluster-60
  - kind-cluster-61
  - kind-cluster-62
  - kind-cluster-63
  - kind-cluster-64
  - kind-cluster-65
  - kind-cluster-66
  - kind-cluster-67
  - kind-cluster-68
  - kind-cluster-69
  - kind-cluster-70
  - kind-cluster-71
  - kind-cluster-72
  - kind-cluster-73
  - kind-cluster-74
  - kind-cluster-75
  - kind-cluster-76
  - kind-cluster-77
  - kind-cluster-78
  - kind-cluster-79
  - kind-cluster-80
