apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.kindSetName }}
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/DavidDaskalo/argocd-bench-list-generator.git
      revision: master
      files:
        - path: 'kinds/*_cr.yaml'
  template:
    metadata:
      name: '{{ .Values.projectName }}-{{ "{{ metadata.name }}" }}'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/DavidDaskalo/argocd-bench-list-generator.git
          targetRevision: master
          path: appset/
          helm:
            valueFiles:
            - 'values.yaml'
            parameters:
              - name: global.clusterName
                value: '{{ "{{ metadata.name }}" }}'
        - repoURL: https://github.com/DavidDaskalo/argocd-bench-list-generator.git
          targetRevision: master
          path: appset2/
          helm:
            valueFiles:
            - 'values.yaml'
            parameters:
              - name: global.clusterName
                value: '{{ "{{ metadata.name }}" }}'
        - repoURL: https://github.com/DavidDaskalo/argocd-bench-list-generator.git
          targetRevision: master
          path: appset4/
          helm:
            valueFiles:
            - 'values.yaml'
            parameters:
              - name: global.clusterName
                value: '{{ "{{ metadata.name }}" }}'
      destination:
        name: 'in-cluster'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true